### ISSUE TITLE
Error on product page.

### ISSUE THREAD

**Issue by ielyanov** [avored/laravel-ecommerce#147]
Hello.
Error on product page
Call to undefined method AvoRed\Related\DataGrid\RelatedProduct::query() (View: C:\OSPanel\domains\ecommerce\themes\avored\default\views\product\view.blade.php)

**Comment by indpurvesh** [comment]
@ielyanov thanks for submitting a bug. It's been fixed. thanks

In your base directory just simply run `composer update`


Yes http://stite.com/install is remove from the package because now as database is growing big. So many people having a bug for `max execution time:  30 sec in PHP` 
In future i might split the PHP process into small piece in future. So in the mean time i have to come up with `php artisan avored:install` command. 

Thanks
