### ISSUE TITLE
Disable the option to remove the admin account.

### ISSUE THREAD

**Issue by ghermans** [avored/laravel-ecommerce#193]
**Describe the bug**
1. No confirmation message is displayed when you destroy a user.
2. If only one admin user exists and you click on destroy it will lock out the user from the system.

**To Reproduce**
1. Go to **System**
2. Click on admin user
3. Click on **destroy**
4. See the result

**Additional context**
1. Add a confirmation model when you click on **destroy**
2. It would be recommended to disable the destroy option when only one admin account exists.

**Comment by indpurvesh** [comment]
I have disabled the Option to destroy user if the AdminUser is Super Admin (created via `avored:admin:make` command)

**Comment by indpurvesh** [comment]
With Regards to Option 1(Add a confirmation model when you click on destroy) I am thinking of doing take me to a page where they see all possible details for that User and then click on Delete instead of just a confirmation alert. 
Something like .NET developer usually does it.

What is your opinion on it? @ghermans

**Comment by ghermans** [comment]
Well the thing is you have 2 links in the table (edit & destroy) in case you want to do the above suggestion then i should suggest to remove the destroy link from the table.

However even if you are on the user details page and you press remove it should give you a confirmation box to be sure that the user will/can be removed, this will give the end user a better user experience.
