### ISSUE TITLE
[Suggestion] backend datagrid to datatables

### ISSUE THREAD

**Issue by ghermans** [avored/laravel-ecommerce#219]
@indpurvesh since i'm busy with changing the back-end theme i was thinking that we maybe could use datatables instead of the current method?

**Comment by indpurvesh** [comment]
I am hoping to implement the whole data grid as in from server side. When someone makes a custom module it's easier for them to add DataGrid on admin. I have implemented some feature on it. Sorting is working and the filter is working too but still, I think I need to add more feature to it.

That's why I don't want to add third-party thing into it because when it comes to customizing it based on your needs it starts getting more complicated to work on someone else feature and plan is to remove jQuery completely and only use VueJs in future only. During VueJs implementation I might implement Datatables but I am not sure at this stage.

For front-end, I am thinking to add a `graphql` support for `react` too but before I think I need to work on Product Return feature.
