### ISSUE TITLE
Import products from csv or xml

### ISSUE THREAD

**Issue by ghermans** [avored/laravel-ecommerce#225]
**Describe the solution you'd like**
Allow staff to import a csv or xml file with products and map the fields to the product database.

**Describe alternatives you've considered**
I would suggest to create a upload form to upload the file, after uploading the file show a table that displays all the data and select boxes above the titles to map it with the database fields

**Comment by nickescobedo** [comment]
I can take this.

Do people really need to allow upload via an XML file? CSV yes, but not sure about XML.

My suggestion would be to allow a user to download a template of what we expect in order to simplify the process. This way we don't need to map database fields. 

Validation should be done to make sure the header rows have the expected column header names.

We can show a preview of maybe the first few records that would be imported.

Thoughts?

**Comment by ghermans** [comment]
Sure feel free to get on the wagon ;)

**Do people really need to allow upload via an XML file? CSV yes, but not sure about XML.**
i'm not 100% sure about that either, i got the idea from working with a customer that is only receiving .csv  and .xml files from his supplier.    

I have created a HTML preview how it could look like:
![snippet1](https://user-images.githubusercontent.com/1594411/47668485-e3583e80-dba8-11e8-99e4-2a3706aa6d9b.PNG)

**Comment by nickescobedo** [comment]
I'll do CSV first.

Can we do static import columns instead of allowing the user to select them? If they are receiving a CSV file they should just be able to change the column name. I'll provide them a link to download a template, so they know what the column names we are expecting.

Dynamic columns increases the complexity without bringing much more value.

For example. What if someone tries to select the same column name for two separate columns? Or if someone has a column name selected from the drop down do I need to get rid of it from the other drop downs so it cannot be selected.

**Comment by indpurvesh** [comment]
Yes we can do static import for a start then add more feature In future

**Comment by ghermans** [comment]
@nickescobedo can you provide us any update of your progress?

**Comment by nickescobedo** [comment]
I haven't started unfortunately. Thanks for asking.
