### ISSUE TITLE
php artisan migrate:refresh Error

### ISSUE THREAD

**Issue by jariesdev** [avored/laravel-ecommerce#329]
This simple error can be duplicate by just running:

`php artisan migrate:refresh`

I Want to use this command to refresh command along with --seed flag for my seeders. Im aware of reinstallation and running 

`php artisan avored:install`

but for my scenario, I can reinstall the avored cause we have custom table added which will be affected.

Anyway, I thank you so much for this great ecommerce framework.

**Comment by indpurvesh** [comment]
@jariesdev bug has been fixed. It's commited in `dev` branch.

**Comment by indpurvesh** [comment]
Ideally i would say if you just do `migrate:refresh --seed` it won't solve many problems because `avored:install` command many stuff then only migration. So if you just use `migrate:refresh` then you still have to do other stuff manually too.

For more information please watch this class `https://github.com/avored/framework/blob/master/src/Support/Console/InstallCommand.php`

**Comment by jariesdev** [comment]
That was fast. Yes, but I just aim to reset the records on the database. I assume that will be ok. Thank you for this update.
