### ISSUE TITLE
select2 - bad work

### ISSUE THREAD

**Issue by j574144** [avored/laravel-ecommerce#334]
Hi.

Please review the select2 in product/basic. This selection not work properly 

![image](https://user-images.githubusercontent.com/30190050/55126837-3e507c00-50dc-11e9-973c-e0ced24f3702.png)

**In addition, you have consider to publish the admin UI?**

**Comment by indpurvesh** [comment]
@j574144 Yes I have had a big list of bug since the last release because the last release was a buggy one because of wrong laravel webpack mix compilation. 

Current, admin panel is missing many javascript libraries that it needed it. So another release is coming soon.

I would suggest to use a previos release would be a better solution in the mean time.

    composer create-project avored/laravel-ecommerce=2.9.8 avored --prefer-dist

**Comment by j574144** [comment]
Thanks.

For this version, also we have error: File not found: /vendor/avored-admin/css/vue.css

**Comment by indpurvesh** [comment]
Update on this issue: 

around 70% of an issue is done.

Replace the Select2 with Vue JS component and some other v-model related fixed done too.

**Comment by j574144** [comment]
Hey thanks for answer.

I have solved it, but I appreciate your effort to remediate on short time and high priority.

I will to write on separated email to me join  your project, this is great and to helped  me
